### ISSUE TITLE
Package Skypat into Debian archive

### ISSUE THREAD

**Issue by szlin** [skymizer/SkyPat#18]
Would you mind letting me package Skypat into Debian archive?

**Comment by Peter-Chang** [comment]
Do you mean that you want to write a script to package SkyPat to a "deb" file?
If you mean so, we have provided a script in "utils/deb/build-deb.sh" to do so.

We still thank your willing to help us.

**Comment by szlin** [comment]
Nope, I mean to package Skypat with Debian way and upload it into Debian archive, thus everyone can install Skypat via official Debian package repository.

**Comment by Peter-Chang** [comment]
Sure. It's our pleasure.

**Comment by gavin09** [comment]
Would you mind creating a new release for the latest SkyPat? I would like to upload the latest SkyPat on Debian : )

**Comment by Peter-Chang** [comment]
Okay. After merging #20, I would create a new release for uploading on Debian.

**Comment by Peter-Chang** [comment]
Hello @szlin & @gavin09 ,

Thanks for your contribution that pushes SkyPat into Debian package server. (https://packages.debian.org/buster/libskypat-dev)

I think that this issue could be closed. Do you have other comments on this issue?

**Comment by szlin** [comment]
@Peter-Chang Nope, I suggest to close this ticket.
